"""Markdown tables from campaign07_frontier's frontier.json (formatting only; no statistics are computed here)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

TYPES = ("first", "after_probe_solved", "after_probe_failed", "after_b1_timeout", "q2_after_H", "q2_after_notH")


def f(x, d=3):
    return "–" if x is None else f"{x:+.{d}f}" if x < 0 else f"{x:.{d}f}"


def fc(e, d=3):
    if e is None or e.get("mean") is None:
        return "–"
    ci = e.get("ci")
    return f"{f(e['mean'], d)} [{f(ci[0], d)}, {f(ci[1], d)}]" if ci else f(e["mean"], d)


def fs(e, d=3):
    if e is None or e.get("mean") is None:
        return "–"
    ci = e.get("ci")
    s = f"{e['mean']:+.{d}f}"
    if ci:
        s += f" [{ci[0]:+.{d}f}, {ci[1]:+.{d}f}]"
    if "signs" in e:
        s += f" {e['signs']['positive']}/{e['signs']['positive'] + e['signs']['negative']}+"
    return s


def redundant(arm):
    """CONS-<c>-pred / -predLRN under phi exact|zero|mean feed the SAME consumer the same channel as CONS-<c>-exact
    under that phi (identical decisions); only their @own rows carry information."""
    base, _, phi = arm.partition("@")
    return base.startswith("CONS-") and base.split("-")[2] in ("pred", "predLRN") and phi != "own" or \
        (base.startswith("CONS-") and phi == "exact") or (base == "SUP-h" and phi == "exact")


def order(arms):
    def k(a):
        base, _, phi = a.partition("@")
        grp = 0 if base.startswith("REF") else 1 if base.startswith("S") and "bank" in base else \
            2 if base.startswith("CONS") else 3
        return (grp, base, ["own", "exact", "zero", "mean"].index(phi) if phi in ("own", "exact", "zero", "mean") else 0)
    return sorted((a for a in arms if not redundant(a)), key=k)


def main(path, out):
    R = json.loads(Path(path).read_text())
    L = ["# e07 P2 frontier tables (generated by campaign07_frontier_tables.py from frontier.json)",
         "", "† post hoc endpoint (added after the pre-defined tables were seen).",
         "Rows omitted as exact duplicates: CONS-*-pred/-predLRN @exact/@zero/@mean (= CONS-*-exact at that phi), "
         "CONS-*@exact and SUP-h@exact where exact is the model's own input."]
    for fam, fr in R["families"].items():
        A = fr["arms"]
        L.append(f"\n### {fam}: pooled over decision types ({fr['octets']} octets)\n")
        L.append("| model@phi | flip | near-miss | invariance | BA_nm | H_sub | FA_sub | **J_sub** | **bias_sub** | J_edge | bias_edge | H_nm† | J_nm† |")
        L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for arm in order(A):
            a = A[arm]["all"]
            L.append(f"| {arm} | " + " | ".join(
                fc(a[e]) if e in ("J_sub", "bias_sub", "BA_nm", "acc_flip", "acc_near_miss") else f(a[e]["mean"])
                for e in ("acc_flip", "acc_near_miss", "acc_invariance", "BA_nm", "H_sub", "FA_sub", "J_sub",
                          "bias_sub", "J_edge", "bias_edge", "H_nm", "J_nm")) + " |")
        L.append(f"\nbase rate of optimum change on 'sub' pairs: {f(A['REF-pistar']['all']['base_sub']['mean'])}"
                 if "REF-pistar" in A else "")
        L.append(f"\n### {fam}: per-seed J_sub / bias_sub (seed index 0-4)\n")
        L.append("| model@phi | J_sub per seed | bias_sub per seed |")
        L.append("|---|---|---|")
        for arm in order(A):
            if arm.startswith("REF"):
                continue
            a = A[arm]["all"]
            L.append(f"| {arm} | {' '.join(f(x) for x in a['J_sub']['per_seed'])} | "
                     f"{' '.join(f(x) for x in a['bias_sub']['per_seed'])} |")
        L.append(f"\n### {fam}: J_sub by decision type (point; CI in frontier.json)\n")
        L.append("| model@phi | " + " | ".join(TYPES) + " |")
        L.append("|---|" + "---|" * len(TYPES))
        for arm in order(A):
            L.append(f"| {arm} | " + " | ".join(f(A[arm][t]["J_sub"]["mean"]) for t in TYPES) + " |")
        L.append(f"\n### {fam}: bias_sub by decision type\n")
        L.append("| model@phi | " + " | ".join(TYPES) + " |")
        L.append("|---|" + "---|" * len(TYPES))
        for arm in order(A):
            L.append(f"| {arm} | " + " | ".join(f(A[arm][t]["bias_sub"]["mean"]) for t in TYPES) + " |")
        for ref in ("S1R1-bank@own", "S0R0-bank@own"):
            L.append(f"\n### {fam}: paired contrasts vs {ref} (pooled; mean [95% CI] positive-seeds/5)\n")
            L.append("| model@phi | ΔJ_sub | Δbias_sub | ΔH_sub | ΔFA_sub | ΔBA_nm | ΔJ_edge | Δflip | Δnear-miss | ΔJ_nm† |")
            L.append("|---|---|---|---|---|---|---|---|---|---|")
            for arm in order(A):
                c = fr["contrasts"].get(f"{arm} - {ref}")
                if c is None or arm.startswith("REF"):
                    continue
                c = c["all"]
                L.append(f"| {arm} | " + " | ".join(fs(c[e]) for e in (
                    "J_sub", "bias_sub", "H_sub", "FA_sub", "BA_nm", "J_edge", "acc_flip", "acc_near_miss", "J_nm")) + " |")
        L.append(f"\n### {fam}: factor-channel contrasts within a model (pooled)\n")
        L.append("| contrast | ΔJ_sub | Δbias_sub | ΔH_sub | ΔFA_sub | ΔBA_nm | Δflip | Δnear-miss | ΔJ_nm† |")
        L.append("|---|---|---|---|---|---|---|---|---|")
        for k in sorted(fr["phi_contrasts"]):
            if k.endswith("@exact") and (k.startswith("CONS-") or k.startswith("SUP-h")):
                continue  # own == exact by construction (0 difference)
            c = fr["phi_contrasts"][k]
            L.append(f"| {k} | " + " | ".join(fs(c[e]) for e in (
                "J_sub", "bias_sub", "H_sub", "FA_sub", "BA_nm", "acc_flip", "acc_near_miss", "J_nm")) + " |")
    Path(out).write_text("\n".join(L) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
