"""S17 independent deterministic TRAIN selection before any diagnostic scores."""
import argparse,collections,gzip,hashlib,json,time
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('repo',type=Path);p.add_argument('--output',type=Path,required=True);a=p.parse_args();t=time.monotonic();root=a.repo/'research/results/campaign-01/semantics';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:[json.loads(s) for s in gzip.open(p,'rt')];load=lambda p:json.load(gzip.open(p,'rt'));folder=root/'s17-calibration-selection';selection=json.loads((folder/'selection.json').read_text());audit=json.loads((folder/'audit.json').read_text());assert sha(folder/'selection.json')==audit['selection_sha256'];excluded={r['alpha_sha256'] for split in ('development','confirmation') for r in read(root/'s15-shape-cache-v2'/(split+'.jsonl.gz'))};arms={}
for arm,quota in [('control',{'4x3':64,'4x4':64}),('mixed',{'3x3':64,'4x3':32,'4x4':32})]:
 path=root/'s15-shape-cache-v2'/f'train_{arm}.jsonl.gz';rows=read(path);expected=sorted(i for cell,n in quota.items() for i in [j for j,r in enumerate(rows) if f"{r['arity']}x{r['facts']}"==cell][:n]);chosen=selection[arm];assert len(expected)==len(set(expected))==128 and [r['index'] for r in chosen]==expected;gold=collections.Counter();actual=collections.Counter()
 for record,i in zip(chosen,expected):
  row=rows[i];assert {k:row[k] for k in ('seed','semantic_sha256','alpha_sha256')}=={k:record[k] for k in ('seed','semantic_sha256','alpha_sha256')};cell=f"{row['arity']}x{row['facts']}";assert record['cell']==cell;assert row['alpha_sha256'] not in excluded;actual[cell]+=1;gold.update(e[2] for e in row['edges'])
 mpath=root/f's15-{arm}-main-v3/manifest.json.gz';m=load(mpath);assert all(m['visits'][i]==8 for i in expected);r=audit['arms'][arm];assert dict(actual)==quota==r['counts'];assert dict(gold)==r['gold_relation_counts'];assert sha(path)==r['train_cache_sha256'];assert sha(mpath)==r['manifest_sha256'];assert m['curves'][-1]['checkpoint_sha256']==r['checkpoint_sha256'];assert m['curves'][-1]['evaluation']['sha256']==r['evaluation_sha256'];assert m['final_state_sha256']==r['model_state_sha256'];arms[arm]=dict(examples=128,counts=quota,gold_relation_counts=dict(gold),all_selected_visits=8,dev_confirmation_overlap=0)
paths=[folder/'selection.json',folder/'audit.json',a.repo/'research/campaigns/extended-01/semantics/S17-select.py',a.repo/'research/campaigns/extended-01/semantics/S17-protocol.md'];assert sha(paths[2])==audit['source_sha256'];assert sha(paths[3])==audit['protocol_sha256'];out=dict(arms=arms,first_qualifying_indices_independently_reproduced=True,no_model_or_scores=True,input_sha256={str(p.relative_to(a.repo)):sha(p) for p in paths},cpu_audit_wall_seconds=time.monotonic()-t,scope='Prospective S15-informed actualTRAIN128 recalibration, fixed mixtures/global policy. Existing primary gates remain failed; no DEV fit, model update, confirmation, selection among alternatives or new promotion gate.')
a.output.write_text(json.dumps(out,indent=2)+'\n');print(out)
