"""S17 fixed TRAIN calibration, frozen raw replay, metrics and phase audit."""
import argparse,ast,base64,collections,gzip,hashlib,json,re,time
from pathlib import Path
import numpy as np
from campaign_semantics_audit import cutoff
from audit_stage11_semantic_text import components,same
p=argparse.ArgumentParser();p.add_argument('repo',type=Path);p.add_argument('--job',choices=('profile','main'),default='profile');p.add_argument('--output',type=Path,required=True);a=p.parse_args();t=time.monotonic();base=a.repo/'research/results/campaign-01/semantics';root=base/f's17-calibration-{a.job}-v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.load(gzip.open(p,'rt'));read=lambda p:[json.loads(line) for line in gzip.open(p,'rt')];m=load(root/'manifest.json.gz');c=m['config'];selection=json.loads((base/'s17-calibration-selection/selection.json').read_text());audit=json.loads((base/'s17-calibration-selection/audit.json').read_text());vocab=json.loads((base/'s15-bindings/original-data-audit.json').read_text())['value_vocabulary'];const={}
for n in ast.parse((a.repo/'src/topoformer/thinking_language.py').read_text()).body:
 if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ('KINDS','ROLES'):const[n.targets[0].id]=ast.literal_eval(n.value)
for group in ('source_sha256','launch_source_sha256'):
 for name,h in c[group].items():assert sha(a.repo/'src/topoformer'/name)==h
config=a.repo/f'configs/campaign-s17-calibration-{a.job}-frozen-v1.json';assert c==json.loads(config.read_text());assert c['calibration_count']==128 and c['dev_per_cell']==(16 if a.job=='profile' else 512);assert m['no_optimizer_or_training'];assert sha(base/'s17-calibration-selection/selection.json')==c['selection_sha256'];assert sha(base/'s17-calibration-selection/audit.json')==c['selection_audit_sha256']
for split,h in c['cache_sha256'].items():assert sha(base/'s15-shape-cache-v2'/(split+'.jsonl.gz'))==h
rows=read(base/'s15-shape-cache-v2/development.jsonl.gz');dev=[r for arity in (3,4) for facts in (3,4) for r in [z for z in rows if (z['arity'],z['facts'])==(arity,facts)][:c['dev_per_cell']]]
# Reuse independently reviewed target construction, not actor/graph compilers.
code=ast.parse(Path(__file__).with_name('campaign_semantic_shape_main_audit.py').read_text());node=next(n for n in code.body if isinstance(n,ast.FunctionDef) and n.name=='gold');exec(compile(ast.Module(body=[node],type_ignores=[]),'<independent-gold>','exec'))
occ=json.loads((root/f's17-calibration-{a.job}-v1.occupancy.json').read_text());clock=dict(line.split('=') for line in (root/f's17-calibration-{a.job}-v1.outer.txt').read_text().splitlines());assert occ['exit_code']==int(clock['exit_code'])==0 and not occ['timed_out'];assert occ['config_sha256']==sha(config) and occ['wrapper_sha256']==c['launch_source_sha256']['campaign_semantics_recalibrate_launch.py'];assert occ['cap_seconds']==c['cap_seconds'];assert [r['arm'] for r in m['artifacts']]==['control','mixed'];graphs=thresholds=calibration_rows=0;timing={}
for rec,binding in zip(m['artifacts'],c['runs']):
 arm=rec['arm'];assert arm==binding['arm'];path=root/rec['artifact'];assert sha(path)==rec['artifact_sha256'];d=load(path);assert len(d['rows'])==len(dev) and len(d['train_rows'])==128;assert rec['new_thresholds']==d['thresholds']==[r['threshold'] for r in d['calibration']];original_path=base/f's15-{arm}-main-v3/evaluation-u28672.json.gz';assert sha(original_path)==binding['evaluation_sha256']==rec['original_evaluation_sha256'];old=load(original_path);oldrows={r['semantic_sha256']:r for r in old['rows']};assert rec['original_thresholds']==old['thresholds'];assert rec['checkpoint_sha256']==audit['arms'][arm]['checkpoint_sha256']==binding['checkpoint_sha256'] and rec['model_state_sha256']==binding['model_state_sha256']==audit['arms'][arm]['model_state_sha256'];train=read(base/'s15-shape-cache-v2'/f'train_{arm}.jsonl.gz');selected=[train[r['index']] for r in selection[arm]];assert rec['calibration_cells']==audit['arms'][arm]['counts'];assert rec['calibration_gold_relation_counts']=={r:audit['arms'][arm]['gold_relation_counts'].get(r,0) for r in const['ROLES']};assert rec['calibration_absent_relations']==[r for r in const['ROLES'] if not rec['calibration_gold_relation_counts'][r]]
 calpath=root/rec['calibration_npz'];assert sha(calpath)==rec['calibration_npz_sha256']==d['calibration_data_sha256'];cal=np.load(calpath)
 for j,r in enumerate(d['calibration']):
  cut,err=cutoff(cal['scores'][:,j],cal['targets'][:,j].astype(bool));assert abs(cut-r['threshold'])<1e-6 and err==r['train_errors'];assert r['positive']==int(cal['targets'][:,j].sum()) and r['negative']==len(cal['targets'])-r['positive'];thresholds+=1
 for i,(row,source) in enumerate(zip(d['train_rows'],selected)):
  assert row['seed']==source['seed'] and row['target']==gold(source);lo,hi=cal['offsets'][i:i+2];pairs=cal['pairs'][lo:hi];presence=np.asarray(row['raw']['presence']);assert np.array_equal(pairs,np.argwhere(presence[:,None]&presence[None,:]));edge=row['target']['edges'];target=np.unpackbits(np.frombuffer(base64.b64decode(edge['packed_b64']),dtype=np.uint8),bitorder='little')[:np.prod(edge['shape'])].reshape(edge['shape']);assert np.array_equal(cal['targets'][lo:hi],target[pairs[:,0],pairs[:,1]]);calibration_rows+=1
  for policy,pred in [('raw',row['raw']),('calibrated',{**row['raw'],'edges':row['calibrated_edges']})]:same(components(pred,row['target']),d['train_metrics'][i][policy])
 for row,source in zip(d['rows'],dev):
  assert row['semantic_sha256']==source['semantic_sha256'];oldrow=oldrows[row['semantic_sha256']];assert row['raw']==oldrow['raw'] and row['target']==oldrow['target']
  for policy,pred in [('raw',row['raw']),('calibrated',{**row['raw'],'edges':row['calibrated_edges']})]:same(components(pred,row['target']),row[policy+'_metrics'])
  graphs+=1
 phases=rec['phase_timing'];assert abs(sum(v for k,v in phases.items() if k!='total_seconds')-phases['total_seconds'])<1e-9;assert rec['setup_seconds']+phases['total_seconds']+rec['verification_seconds']<=rec['seconds']+.01;timing[arm]=dict(setup_seconds=rec['setup_seconds'],**phases,verification_seconds=rec['verification_seconds'],endpoint_seconds=rec['seconds'])
outer=float(clock['elapsed_seconds']);out=dict(job=a.job,train_calibration_graphs_verified=calibration_rows,relation_cutoffs_recomputed=thresholds,dev_graphs_reconstructed=graphs,all_raw_targets_exact_original_replay=True,global_threshold_policy_all_cells=True,frozen_endpoints_source_and_selection_verified=True,phase_timing=timing,inner_occupancy_seconds=occ['process_occupancy_seconds'],outer_seconds=outer,conservative_charge_seconds=round(outer+.01,2),input_sha256={str(p.relative_to(a.repo)):sha(p) for p in root.rglob('*') if p.is_file()},cpu_audit_wall_seconds=time.monotonic()-t,scope='FixedactualTRAIN128 perendpoint and unchanged threshold algorithm; noDEV fitting or profile-based recipe selection. Profile checks timing/contracts only; historical S15 gates unchanged. Maincap/freeze require separate review.')
a.output.write_text(json.dumps(out,indent=2)+'\n');print({k:v for k,v in out.items() if k!='input_sha256'})
