"""S16 timing-only profile provenance and prospective main cost audit."""
import argparse,gzip,hashlib,json,math,time
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('repo',type=Path);p.add_argument('--semantics',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();t=time.monotonic();root=a.repo/'research/results/campaign-01/semantics/s16-profile';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.load(gzip.open(p,'rt'));inventory=json.loads((root/'archive-sha256.json').read_text())
for path,h in inventory.items():assert sha(root/path)==h
m=load(root/'s16-normalized-profile/manifest.json.gz');c=m['config'];config=a.repo/'research/campaigns/extended-01/semantics/S16-profile-frozen-v2.json';assert c==json.loads(config.read_text()) and sha(config)=='8dfb3326c21c410064267fbf9122a3c1e373707f89a5b1dfb838a340f83807d1'
for name,h in c['source_sha256'].items():assert sha(a.repo/'src/topoformer'/name)==h
occ=json.loads((root/'s16-profile-launch.occupancy.json').read_text());start=json.loads((root/'s16-profile-launch.started.json').read_text());completion=json.loads((root/'s16-normalized-profile/completion.json').read_text());outer=json.loads((root/'outer-command-accounting.json').read_text());cost=json.loads((root/'main-cost-proposal.json').read_text());clock=dict(line.split('=') for line in (root/'s16-profile-launch.outer.txt').read_text().splitlines());assert int(clock['exit_code'])==occ['exit_code']==outer['exit_code']==0 and not occ['timed_out'] and not occ['error'];assert occ['gpu_processes'].strip()=='' and completion['success'];assert occ['config_sha256']==start['config_sha256']==sha(config);assert occ['wrapper_sha256']==c['source_sha256']['campaign_semantics_s16_launch.py'];assert occ['cap_seconds']==60;assert hashlib.sha256(outer['command'].encode()).hexdigest()==outer['command_sha256'];assert float(clock['elapsed_seconds'])==outer['outer_seconds']==25.27 and outer['conservative_charge_seconds']==25.28;assert m['process_seconds']<=completion['process_seconds']<=occ['process_occupancy_seconds']<=25.28
assert [(r['seed'],r['arm']) for r in m['artifacts']]==[(s,arm) for s in (701,702,703) for arm in ('constant','decay')];sums={k:0. for k in m['artifacts'][0]['timing']}
for r,b in zip(m['artifacts'],c['primary_matrix']):
 assert r['examples']==8 and r['checkpoint_sha256']==b['checkpoint_sha256'];assert r['tensor_before_sha256']==r['tensor_after_sha256'];assert len(r['output_sha256'])==64 and 'summary' not in r and 'artifact' not in r
 primary=a.semantics/f'research/results/campaign-01/semantics/s12-{r["arm"]}-{r["seed"]}/evaluation-u24576.json.gz';assert sha(primary)==r['primary_sha256'];assert load(primary)['thresholds']==r['thresholds']
 assert all(math.isfinite(v) and v>=0 for v in r['timing'].values());assert r['timing']['scoring_seconds']==0;assert sum(r['timing'].values())<=r['seconds']
 for k,v in r['timing'].items():sums[k]+=v
assert sums==cost['stage_sums_seconds'];variable=sums['forward_decode_seconds']+sums['packing_hash_seconds'];fixed=25.28-variable;cold=fixed+variable*128;warm=fixed+m['artifacts'][0]['timing']['forward_decode_seconds']+sum(r['timing']['forward_decode_seconds'] for r in m['artifacts'][1:])/40*6144+sums['packing_hash_seconds']*128
assert abs(fixed-cost['fixed_outer_residual_seconds'])<1e-9 and abs(cold-cost['cold_inclusive_linear_projection_seconds'])<1e-9 and abs(warm-cost['warm_projection_seconds'])<1e-9;assert cost['proposed_main_cap_seconds']==480 and not cost['automatic_extension'];total=cold+cost['unprofiled_scoring_allowance_seconds']+cost['unprofiled_export_allowance_seconds'];assert total<480
out=dict(endpoints=6,forwards=48,outcome_metrics_not_exported=True,all_frozen_hashes_thresholds_unchanged=True,outer_seconds=25.27,conservative_charge_seconds=25.28,wrapper_seconds=occ['process_occupancy_seconds'],preflight_seconds=m['preflight_seconds'],timing_stage_sums=sums,warm_projection_seconds=warm,cold_inclusive_projection_seconds=cold,unmeasured_scoring_export_allowances_seconds=150,planning_total_seconds=total,main_cap_480_supported_for_separate_freeze_release=True,input_sha256={str((root/path).relative_to(a.repo)):h for path,h in inventory.items()},cpu_audit_wall_seconds=time.monotonic()-t,scope='Timing/contracts only, no policy/outcome selection. Cold-inclusive scaling plus120s scoring/30s export are planning estimates, not a runtime bound. Main allsix1024/source unchanged needs immutable cap freeze and separate root release; timeout cannot silently extend or drop endpoints.')
a.output.write_text(json.dumps(out,indent=2)+'\n');print({k:v for k,v in out.items() if k!='input_sha256'})
