"""Independent S18 profile numerical contracts and conservative phase arithmetic."""
import argparse,ast,base64,gzip,hashlib,json,re,time
from pathlib import Path
import numpy as np
from campaign_semantics_audit import cutoff
from audit_stage11_semantic_text import components,same
p=argparse.ArgumentParser();p.add_argument('repo',type=Path);p.add_argument('--review',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();tick=time.monotonic();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();load=lambda p:json.load(gzip.open(p,'rt'));read=lambda p:[json.loads(s) for s in gzip.open(p,'rt')];base=a.repo/'research/results/campaign-01/semantics';archive=base/'s18-profile';run=archive/'s18-profile-v1';m=load(run/'manifest.json.gz');c=m['config'];config=a.repo/'configs/campaign-s18-profile-frozen-v2.json';assert c==json.loads(config.read_text());assert sha(config)=='418864b31d66d299b3dd5f6e7470d1dec4aa5304b76856ea7d1098e4b7ebdd08'
for path,h in json.loads((archive/'archive-sha256.json').read_text()).items():assert sha(archive/path)==h
for name,h in c['source_sha256'].items():assert sha(a.repo/'src/topoformer'/name)==h
occ=json.loads((archive/'s18-profile-launch.occupancy.json').read_text());clock=dict(s.split('=') for s in (archive/'s18-profile-launch.outer.txt').read_text().splitlines());assert occ['exit_code']==int(clock['exit_code'])==0 and not occ['timed_out'];assert occ['config_sha256']==sha(config) and occ['wrapper_sha256']==c['source_sha256']['campaign_semantics_s18_launch.py'];assert occ['cap_seconds']==180;assert [r['arm'] for r in m['results']]==['context','workspace_control'];assert json.loads((run/'completion.json').read_text())['success']
state=json.loads((a.review/'S18-profile-state-audit.json').read_text());vocab=json.loads((base/'s15-bindings/original-data-audit.json').read_text())['value_vocabulary'];const={}
for n in ast.parse((a.repo/'src/topoformer/thinking_language.py').read_text()).body:
 if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ('KINDS','ROLES'):const[n.targets[0].id]=ast.literal_eval(n.value)
code=ast.parse(Path(__file__).with_name('campaign_semantic_shape_main_audit.py').read_text());node=next(n for n in code.body if isinstance(n,ast.FunctionDef) and n.name=='gold');exec(compile(ast.Module(body=[node],type_ignores=[]),'<independent-gold>','exec'))
rows=read(base/'s15-shape-cache-v2/development.jsonl.gz');dev=[r for arity in (3,4) for facts in (3,4) for r in [x for x in rows if (x['arity'],x['facts'])==(arity,facts)][:16]];mixed=read(base/'s15-shape-cache-v2/train_mixed.jsonl.gz');sel=json.loads((base/'s17-calibration-selection/selection.json').read_text())['mixed'];train={'matched':[mixed[r['index']] for r in sel],'historical':read(base/'s01-data/train.jsonl.gz')[:128]};graphs=cuts=0;forecasts=[];raw={}
for result in m['results']:
 arm=result['arm'];assert result==load(run/arm/'manifest.json.gz');assert [r['added_update'] for r in result['curves']]==[0,20]
 for curve in result['curves']:
  step=curve['added_update'];u=24576+step;assert curve['update']==u and curve['added_presentations']==step*8;remote=c['output_dir']+'/'+arm+f'/model-u{u}.pt';assert state['checkpoint_sha256'][remote]==curve['checkpoint_sha256']
  for policy in ('matched','historical'):
   rec=curve[policy];path=run/arm/f'{policy}-u{u}'/rec['artifact'];assert sha(path)==rec['sha256'];d=load(path);assert len(d['rows'])==64 and len(d['train_rows'])==128 and len(d['train_metrics'])==128;assert d['thresholds']==[x['threshold'] for x in d['calibration']];npz=path.parent/d['calibration_data_artifact'];assert sha(npz)==d['calibration_data_sha256'];cal=np.load(npz)
   for j,r in enumerate(d['calibration']):
    cut,err=cutoff(cal['scores'][:,j],cal['targets'][:,j].astype(bool));assert abs(cut-r['threshold'])<1e-6 and err==r['train_errors'];assert r['positive']==int(cal['targets'][:,j].sum()) and r['negative']==len(cal['targets'])-r['positive'];cuts+=1
   for i,(row,source) in enumerate(zip(d['train_rows'],train[policy],strict=True)):
    assert row['seed']==source['seed'] and row['target']==gold(source);lo,hi=cal['offsets'][i:i+2];pairs=cal['pairs'][lo:hi];presence=np.asarray(row['raw']['presence']);assert np.array_equal(pairs,np.argwhere(presence[:,None]&presence[None,:]));edge=row['target']['edges'];target=np.unpackbits(np.frombuffer(base64.b64decode(edge['packed_b64']),dtype=np.uint8),bitorder='little')[:np.prod(edge['shape'])].reshape(edge['shape']);assert np.array_equal(cal['targets'][lo:hi],target[pairs[:,0],pairs[:,1]])
    for label,pred in [('raw',row['raw']),('calibrated',{**row['raw'],'edges':row['calibrated_edges']})]:same(components(pred,row['target']),d['train_metrics'][i][label])
    graphs+=1
   for row,source in zip(d['rows'],dev,strict=True):
    assert row['semantic_sha256']==source['semantic_sha256'] and row['target']==gold(source);key=(arm,step,row['semantic_sha256']);value=(row['raw'],row['target']);assert key not in raw or raw[key]==value;raw[key]=value
    for label,pred in [('raw',row['raw']),('calibrated',{**row['raw'],'edges':row['calibrated_edges']})]:same(components(pred,row['target']),row[label+'_metrics'])
    graphs+=1
   assert abs(sum(rec['timing'].values())-rec['whole_evaluation_seconds'])<.01
 timings=[q[p]['timing'] for q in result['curves'] for p in ('matched','historical')];terms=dict(optimizer=result['training_seconds']*204.8,calibration_trainpanel_and_posthash=sum(v['calibration_trainpanel_seconds']+v['post_state_hash_seconds'] for v in timings)*2,dev=sum(v['dev_seconds'] for v in timings)*64,export=sum(v['export_seconds'] for v in timings)*64,checkpoint_export=sum(q['checkpoint_export_seconds'] for q in result['curves'])*2,setup=result['setup_seconds']);forecasts.append(dict(arm=arm,profile_training_seconds=result['training_seconds'],terms=terms,subtotal=sum(terms.values())))
cost=json.loads((archive/'cost-proposal.json').read_text());assert forecasts==cost['forecasts'];assert abs(sum(v['subtotal'] for v in forecasts)+400-cost['main_planning_estimate_seconds'])<1e-9;assert cost['proposed_main_cap_seconds']==4000 and cost['proposed_reference_cap_seconds']==240;prior=load(base/'s17-calibration-main-v1/manifest.json.gz');reference=3*max(v['seconds'] for v in prior['artifacts']);assert abs(reference-cost['reference_three_checkpoint_measured_basis_seconds'])<1e-9;outer=float(clock['elapsed_seconds']);assert cost['profile_outer_seconds']==outer and cost['conservative_charge_seconds']==round(outer+.01,2);assert cost['profile_wrapper_seconds']==occ['process_occupancy_seconds'];assert occ['process_occupancy_seconds']>=m['process_seconds']
out=dict(graphs_reconstructed=graphs,relation_cutoffs_recomputed=cuts,both_policy_raw_targets_equal=True,state_audit_reused=True,archive_hashes_verified=True,main_estimate_seconds=cost['main_planning_estimate_seconds'],reference_estimate_seconds=reference+35,main_cap_supported=4000,reference_cap_supported=240,outer_seconds=outer,conservative_charge_seconds=cost['conservative_charge_seconds'],input_sha256={str(p.relative_to(a.repo)):sha(p) for p in archive.rglob('*') if p.is_file()},cpu_audit_wall_seconds=time.monotonic()-tick,scope='Mechanical/numerical and timing audit only; no profile outcome selection or promotion. Forecasts not deterministic bounds; entire export including slow control startup retained at64x, optimizer204.8x and fixed calibration2x, plus400s engineering reserve. Separate prospective freezes/root release required.')
a.output.write_text(json.dumps(out,indent=2)+'\n');print({k:v for k,v in out.items() if k!='input_sha256'})
