"""Independent complete S18 reused-reference numeric audit; CPU no actor."""
import argparse,ast,base64,gzip,hashlib,json,re,time
from pathlib import Path
import numpy as np
from campaign_semantics_audit import cutoff
from audit_stage11_semantic_text import components,same
p=argparse.ArgumentParser();p.add_argument('repo',type=Path);p.add_argument('--archive',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();tick=time.monotonic();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();load=lambda p:json.load(gzip.open(p,'rt'));read=lambda p:[json.loads(s) for s in gzip.open(p,'rt')];base=a.repo/'research/results/campaign-01/semantics';run=a.archive/'s18-reference-v2';m=load(run/'manifest.json.gz');c=m['config'];assert hashlib.sha256(json.dumps(c,indent=2).encode()+b'\n').hexdigest()=='e99ee70e99d92e921765bf8c7f8eea2064f78f869b3c9157f890b7322f937cab'
for path,h in json.loads((a.archive/'archive-sha256.json').read_text()).items():assert sha(a.archive/path)==h
occ=json.loads((a.archive/'s18-reference-v2-launch.occupancy.json').read_text());clock=dict(s.split('=') for s in (a.archive/'s18-reference-v2-launch.outer.txt').read_text().splitlines() if '=' in s);assert occ['exit_code']==int(clock['exit_code'])==0 and not occ['timed_out'];assert occ['config_sha256']=='e99ee70e99d92e921765bf8c7f8eea2064f78f869b3c9157f890b7322f937cab' and occ['wrapper_sha256']==c['source_sha256']['campaign_semantics_s18_launch.py'];assert occ['cap_seconds']==240;assert len(m['results'])==1 and m['results'][0]['no_optimizer_or_training'];result=m['results'][0];assert [r['added_update'] for r in result['curves']]==[0,1024,2048];oldmanifest=load(base/'s15-mixed-main-v3/manifest.json.gz');vocab=json.loads((base/'s15-bindings/original-data-audit.json').read_text())['value_vocabulary'];const={}
for n in ast.parse((a.repo/'src/topoformer/thinking_language.py').read_text()).body:
 if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ('KINDS','ROLES'):const[n.targets[0].id]=ast.literal_eval(n.value)
code=ast.parse(Path(__file__).with_name('campaign_semantic_shape_main_audit.py').read_text());node=next(n for n in code.body if isinstance(n,ast.FunctionDef) and n.name=='gold');exec(compile(ast.Module(body=[node],type_ignores=[]),'<independent-gold>','exec'))
rows=read(base/'s15-shape-cache-v2/development.jsonl.gz');dev={r['semantic_sha256']:r for r in rows};mixed=read(base/'s15-shape-cache-v2/train_mixed.jsonl.gz');sel=json.loads((base/'s17-calibration-selection/selection.json').read_text())['mixed'];train=[mixed[r['index']] for r in sel];graphs=cuts=0;counts={};checkpoint_bindings={}
for curve,oldcurve in zip(result['curves'],oldmanifest['curves'][:3],strict=True):
 step=curve['added_update'];u=24576+step;assert curve['checkpoint']['sha256']==oldcurve['checkpoint_sha256'] and curve['raw_target_replay_exact'];checkpoint_bindings[str(u)]=dict(**curve['checkpoint'],model_state_sha256=curve['model_state_sha256']);rec=curve['evaluation'];path=run/f'u{u}'/rec['artifact'];assert sha(path)==rec['sha256'];d=load(path);oldpath=base/f's15-mixed-main-v3/evaluation-u{u}.json.gz';assert sha(oldpath)==oldcurve['evaluation']['sha256'];old=load(oldpath);N={r['semantic_sha256']:r for r in d['rows']};O={r['semantic_sha256']:r for r in old['rows']};assert len(N)==len(O)==len(d['rows'])==len(old['rows'])==2048 and N.keys()==O.keys()==dev.keys();assert len(d['train_rows'])==len(d['train_metrics'])==128;assert d['thresholds']==[x['threshold'] for x in d['calibration']];npz=path.parent/d['calibration_data_artifact'];assert sha(npz)==d['calibration_data_sha256'];cal=np.load(npz)
 for j,r in enumerate(d['calibration']):
  cut,err=cutoff(cal['scores'][:,j],cal['targets'][:,j].astype(bool));assert abs(cut-r['threshold'])<1e-6 and err==r['train_errors'];assert r['positive']==int(cal['targets'][:,j].sum()) and r['negative']==len(cal['targets'])-r['positive'];cuts+=1
 for i,(row,source) in enumerate(zip(d['train_rows'],train,strict=True)):
  assert row['seed']==source['seed'] and row['target']==gold(source);lo,hi=cal['offsets'][i:i+2];pairs=cal['pairs'][lo:hi];presence=np.asarray(row['raw']['presence']);assert np.array_equal(pairs,np.argwhere(presence[:,None]&presence[None,:]));edge=row['target']['edges'];target=np.unpackbits(np.frombuffer(base64.b64decode(edge['packed_b64']),dtype=np.uint8),bitorder='little')[:np.prod(edge['shape'])].reshape(edge['shape']);assert np.array_equal(cal['targets'][lo:hi],target[pairs[:,0],pairs[:,1]])
  for label,pred in [('raw',row['raw']),('calibrated',{**row['raw'],'edges':row['calibrated_edges']})]:same(components(pred,row['target']),d['train_metrics'][i][label])
  graphs+=1
 cellcounts={cell:dict(raw=0,matched=0) for cell in ('3x3','3x4','4x3','4x4')}
 for event,row in N.items():
  source=dev[event];assert row['raw']==O[event]['raw'] and row['target']==O[event]['target']==gold(source) and row['raw_metrics']==O[event]['raw_metrics'];cell=f"{source['arity']}x{source['facts']}"
  for label,pred in [('raw',row['raw']),('calibrated',{**row['raw'],'edges':row['calibrated_edges']})]:same(components(pred,row['target']),row[label+'_metrics']);cellcounts[cell]['raw' if label=='raw' else 'matched']+=int(row[label+'_metrics']['semantic_equivalence'])
  graphs+=1
 counts[str(step)]=cellcounts;assert abs(sum(rec['timing'].values())-rec['whole_evaluation_seconds'])<.01
out=dict(graphs_reconstructed=graphs,dev_raw_target_and_metrics_replayed=6144,train128_fixed_selection_each_checkpoint=True,relation_cutoffs_recomputed=cuts,checkpoint_bindings=checkpoint_bindings,counts=counts,outer_seconds=float(clock['elapsed_seconds']),conservative_charge_seconds=round(float(clock['elapsed_seconds'])+.01,2),input_sha256={str(p)[str(p).index('research/'):]:sha(p) for p in a.archive.rglob('*') if p.is_file()},cpu_audit_wall_seconds=time.monotonic()-tick,scope='Complete3frozen early checkpoints, all2048DEV and fixed actualTRAIN128. Raw replay keyed by unique semanticID; global cutoffs recomputed. Final baseline reused from S17. Failed63.93cost remains separate; repeatedfirstcurve charged; no new model calls or selection.')
a.output.write_text(json.dumps(out,indent=2)+'\n');print({k:v for k,v in out.items() if k not in ('input_sha256','checkpoint_bindings')})
