"""S18 complete archive/state linkage and accounting; no outcome inference."""
import argparse,gzip,hashlib,json,time
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('archive',type=Path);p.add_argument('--review',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();t=time.monotonic();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.load(gzip.open(p,'rt'));hashes=json.loads((a.archive/'archive-sha256.json').read_text())
for name,h in hashes.items():assert sha(a.archive/name)==h
m=load(a.archive/'s18-main-v1/manifest.json.gz');cost=json.loads((a.archive/'phase-costs.json').read_text());states={arm:json.loads((a.review/f'S18-main-{label}-state-audit.json').read_text()) for arm,label in [('context','context'),('workspace_control','control')]};ledger=json.loads((a.archive/'retained-checkpoints.json').read_text());assert len(ledger)==8
for r in ledger:assert states[r['arm']]['input_sha256'][r['path']]==r['sha256'] and r['bytes']==694388856
for result,record in zip(m['results'],cost['arms'],strict=True):
 assert result['arm']==record['arm'];assert states[result['arm']]['manifest_sha256']==sha(a.archive/'s18-main-v1'/result['arm']/'manifest.json.gz');assert result['training_seconds']==record['optimizer_seconds'];assert abs(record['optimizer_ms_per_update']-1000*result['training_seconds']/4096)<1e-9;assert record['setup_seconds']==result['setup_seconds'];assert record['checkpoint_export_seconds']==sum(c['checkpoint_export_seconds'] for c in result['curves']);assert record['parameters']==states[result['arm']]['parameter_count'];assert all(record['exposures'][k]==result[k] for k in record['exposures'])
 for policy,r in record['policies'].items():
  assert r['whole_evaluation_seconds']==sum(c[policy]['whole_evaluation_seconds'] for c in result['curves'])
  for key in ('calibration_trainpanel_seconds','dev_seconds','export_seconds','post_state_hash_seconds'):assert r[key]==sum(c[policy]['timing'][key] for c in result['curves'])
  assert r['dev_examples']==8192 and r['calibration_panel_example_evaluations']==512;assert abs(r['dev_ms_per_example_including_metrics_and_packing']-r['dev_seconds']*1000/8192)<1e-9
occ=json.loads((a.archive/'s18-main-v2-launch.occupancy.json').read_text());assert cost['wrapper_seconds']==occ['process_occupancy_seconds'];assert cost['child_process_seconds']==m['process_seconds'];assert cost['preflight_seconds']==m['preflight_seconds'];assert cost['peak_cuda_allocated']==m['peak_cuda_allocated'];assert cost['maxrss_kib']==m['process_maxrss_kib'];assert cost['outer_seconds']==1940.07 and cost['conservative_charge_seconds']==1940.08;assert cost['reference_separate_charge_seconds']==155.1 and cost['failed_reference_separate_charge_seconds']==63.93 and cost['profile_separate_charge_seconds']==86.53
out=dict(archive_files_verified=len(hashes),all_eight_checkpoints_match_independent_state_audits=True,phase_costs_and_denominators_exact=True,total_new_S18_occupancy_seconds=round(1940.08+155.1+63.93+86.53,2),historical_reused_training_seconds=484.14140757126734,input_sha256={str(p)[str(p).index('research/'):]:sha(p) for p in [a.archive/'archive-sha256.json',a.archive/'phase-costs.json',a.archive/'retained-checkpoints.json',a.archive/'s18-main-v1/manifest.json.gz']},cpu_audit_wall_seconds=time.monotonic()-t,scope='Verified measured optimizer/eval/export scopes and full outer accounting; eval latency includes decoding/metrics/packing, MAC estimates not FLOPs or equal runtime. Historical original cost retained separately; no outcome claim.')
a.output.write_text(json.dumps(out,indent=2)+'\n');print(out)
